assign hashfn_name to BloomFilter object
jaybaird/python-bloomfilter pull request #31
Opened 2018-04-09 20:11 UTC by groovecoder

We are using `pybloom.BloomFilter` to construct a multi-layer filter cascade which we will then write to a file. We need to include each layer's hash function in the file.

This code introduces a `hashfn_name` property to `BloomFilter`, and assigns the selected `hashfn.__name__` to it.

2018-04-09 23:35 UTC, joseph-fox requested changes
This is an useful PR. Just a few questions.

If you could make a PR against https://github.com/joseph-fox/python-bloomfilter, I can merge it.

2018-04-09 23:35 UTC, joseph-fox commented on pybloom/pybloom.py
> +        self.make_hashes, self.hashfn_name = make_hashfuncs(self.num_slices, self.bits_per_slice)
Wound't it be slightly more useful to return the hash function itself and let the caller to decide how the hash function is used (get the hash function name in this case)?

2018-04-09 23:35 UTC, joseph-fox commented on pybloom/pybloom.py
> +    return _make_hashfuncs, hashfn_name
Do the variable names ( `_make_hashfuncs` and `hashfn_name`) seem a bit confusing here - the singular and plural nouns seem a bit contradict to each other? 

`make_hashfuncs` essentially returns a hash maker.  I think we could do a bit name refactoring here to reflect the fact that one is hash maker and the other is the hash function used by the hash maker.

2018-04-09 23:35 UTC, joseph-fox commented on pybloom/pybloom.py
> +        self.make_hashes, self.hashfn_name = make_hashfuncs(self.num_slices, self.bits_per_slice)
Would it be useful to have a simple unit test to ensure that `make_hashfuncs` returns 2 params and what they are?

2018-04-10 03:06 UTC, groovecoder commented
Updated. I also tinkered the `pytest` code a bit so now `tox` runs both the explicit tests and the doctests in the module.

2018-04-10 03:08 UTC, groovecoder commented
Also created https://github.com/joseph-fox/python-bloomfilter/pull/17.

2018-04-10 15:48 UTC, groovecoder commented
Closing; moved to https://github.com/joseph-fox/python-bloomfilter/pull/17.

2018-04-10 15:48 UTC, closed without merging